# NumPy Array

In [2]:
import numpy as np

In [3]:
x = [1, 2, 3, 4, 5]  # Create a Python list with values 1 through 5

y = np.array(x)  # Convert the Python list to a NumPy array

print(y)  # Print the NumPy array: [1 2 3 4 5]

print(y.ndim)  # Print the number of dimensions: 1 (since it's a 1D array)


[1 2 3 4 5]
1


Create a 2D NumPy array (2x4)

In [4]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])  
print(arr2)  # Print the 2D array
print(arr2.ndim)  # Print the number of dimensions: 2 (since it's a 2D array)

[[1 2 3 4]
 [5 6 7 8]]
2


Create a 3D NumPy array

In [6]:
arr3 = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [4, 5, 6, 7]]])  
print(arr3)  # Print the 3D array
print(arr3.ndim)  # Print the number of dimensions: 3 (since it's a 3D array)


[[[1 2 3 4]
  [5 6 7 8]
  [4 5 6 7]]]
3


Create a NumPy array with at least 10 dimensions.

In [7]:
arrn = np.array([1, 2, 3, 4], ndmin=10)  
# The `ndmin` parameter specifies the minimum number of dimensions.

print(arrn)  # Print the 10D array. The array will be "stretched" to have 10 dimensions.

print(arrn.ndim)  # Print the number of dimensions: 10 


[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# Zeros()
The zeros() function in NumPy creates an array filled with zeros. Here's a brief overview with examples and comments:

In [ ]:
# Create a 1D array of zeros with length 5
arr1 = np.zeros(5)
print(arr1)  # Output: [0. 0. 0. 0. 0.]

# Create a 2D array of zeros with shape (3, 4)
arr2 = np.zeros((3, 4))
print(arr2)  
# Output:
# [[0. 0. 0. 0.]
#  [0. 0. 0. 0.]
#  [0. 0. 0. 0.]]

# Create a 3D array of zeros with shape (2, 3, 4)
arr3 = np.zeros((2, 3, 4))
print(arr3)  
# Output:
# [[[0. 0. 0. 0.]
#   [0. 0. 0. 0.]
#   [0. 0. 0. 0.]]
# 
#  [[0. 0. 0. 0.]
#   [0. 0. 0. 0.]
#   [0. 0. 0. 0.]]]


# Ones()
The ones() function in NumPy creates an array filled with ones. Here's how to use it:

In [ ]:
# Create a 1D array of ones with length 5
arr1 = np.ones(5)
print(arr1)  
# Output: [1. 1. 1. 1. 1.]
# A 1D array with five elements, all set to 1.0.

# Create a 2D array of ones with shape (3, 4)
arr2 = np.ones((3, 4))
print(arr2)  
# Output:
# [[1. 1. 1. 1.]
#  [1. 1. 1. 1.]
#  [1. 1. 1. 1.]]
# A 2D array with 3 rows and 4 columns, all set to 1.0.

# Create a 3D array of ones with shape (2, 3, 4)
arr3 = np.ones((2, 3, 4))
print(arr3)  
# Output:
# [[[1. 1. 1. 1.]
#   [1. 1. 1. 1.]
#   [1. 1. 1. 1.]]
# 
#  [[1. 1. 1. 1.]
#   [1. 1. 1. 1.]
#   [1. 1. 1. 1.]]]
# A 3D array with dimensions 2x3x4, all set to 1.0.

# Create a 2D array of ones with integer type
arr_int = np.ones((2, 3), dtype=int)
print(arr_int)  
# Output:
# [[1 1 1]
#  [1 1 1]]
# A 2D array with 2 rows and 3 columns, all set to 1 (integers).


# Empty()
The empty() function in NumPy creates an array without initializing its entries, meaning the array contains whatever values were previously in memory. This can be faster than functions like zeros() or ones() but the contents are unpredictable.

In [6]:
# Create a 1D array with 4 uninitialized elements

ar_empty = np.empty(4)
print(ar_empty)  

# Output: [random values, values left uninitialized]
# The array contains values that were already in memory. The contents are not predictable.


[0.0000000e+000 1.1718976e-311 1.1718976e-311 1.1718976e-311]


# Range()
The range() function is a built-in Python function used to generate a sequence of numbers. It is commonly used in loops to iterate over a sequence of numbers. NumPy also has similar functionality with np.arange(), but here’s a brief overview of range() in Python:



In [ ]:
# Create a NumPy array with values from 0 to 5
ar_rn = np.arange(6)
print(ar_rn)  
# Output: [0 1 2 3 4 5]
# `np.arange(6)` generates an array starting from 0 up to, but not including, 6.

Create a 1D array with values from 2 to 10 (exclusive), with a step of 3

In [ ]:
ar_rn = np.arange(2, 10, 3)
print(ar_rn)  
# Output: [2 5 8]
# The array starts at 2, ends before 10, with a step of 3 between values.


# Diagonal element
The eye() function in NumPy creates a 2D array with ones on the diagonal and zeros elsewhere. It is often used to create identity matrices.

np.eye(n) creates an n x n identity matrix, where n is the number of rows and columns.

All the diagonal elements are set to 1, and all off-diagonal elements are set to 0.

In [ ]:
# Create a 2D identity matrix of size 3x3
identity_matrix = np.eye(3)
print(identity_matrix)  
# Output:
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]
# An identity matrix where diagonal elements are 1 and off-diagonal elements are 0.

# Create a 2D identity matrix of size 4x4
identity_matrix_4x4 = np.eye(4)
print(identity_matrix_4x4)  
# Output:
# [[1. 0. 0. 0.]
#  [0. 1. 0. 0.]
#  [0. 0. 1. 0.]
#  [0. 0. 0. 1.]]
# A larger identity matrix with 4 rows and 4 columns.


# linspace()
The linspace() function in NumPy generates evenly spaced values over a specified range. It is useful for creating sequences of numbers with a defined number of intervals between them.

In [ ]:
# The np.linspace(0, 10, num=5) function call generates 5 equally spaced values starting from 0 to 10.
# Create an array with 5 evenly spaced values between 0 and 10
ar_lin = np.linspace(0, 10, num=5)
print(ar_lin)  

# Output: [ 0.   2.5  5.   7.5 10. ]
# Five values evenly spaced from 0 to 10, inclusive.

# rand()
The rand() function in NumPy generates an array of random numbers from a uniform distribution over [0, 1). This function is part of the numpy.random module.

In [ ]:
# Create a 1D array with 4 random values between 0 and 1
ar_rn = np.random.rand(4)
print(ar_rn)  
# Output: Array with 4 random values between 0 and 1, e.g., [0.123 0.456 0.789 0.234]


Create a 2D array with shape (4, 5), filled with random values between 0 and 1

In [16]:
ar_rn = np.random.rand(4, 5)
print(ar_rn) 
# A 2D array with 4 rows and 5 columns, with each element being a random number between 0 and 1.

[[0.99543489 0.61642869 0.05649785 0.35675116 0.63259332]
 [0.02361425 0.99392222 0.43812759 0.61544032 0.60775206]
 [0.23389869 0.82277357 0.34280198 0.008027   0.58129946]
 [0.10970954 0.75291662 0.67002587 0.80069271 0.19843347]]


# randn()
The function is used to generate a random value close to zero,they may be return positive or negative numbers. 

In [17]:
# Create a 1D array with 4 random values from a standard normal distribution
ar_rn = np.random.randn(4)
print(ar_rn)  
# Output: Array with 4 random values drawn from a standard normal distribution (mean 0, variance 1).

[-1.31370147  0.76447443  0.06479253  1.55710285]


# ranf()
The function for doing random sampling in numpy.It retuns an array of specified shape and fill it with random floats in the half open interval [0.0 1.0).

In [18]:
# Create a 1D array with 4 random values between 0 and 1
ar_rn = np.random.ranf(4)
print(ar_rn)  
# Output: Array with 4 random numbers between 0 and 1

[0.00180204 0.97219664 0.46528434 0.68055384]


# randint()
The function for used to generate a random number between given range.

In [19]:
# Create a 1D array with 5 random integers between 1 and 100 (inclusive of 1, exclusive of 100)
ar_rn = np.random.randint(1, 100, 5)
print(ar_rn)  
# Output: Array with 5 random integers from 1 to 99

[ 5 34 60  2 95]


# Data types

In [7]:
# Create a NumPy array with integer values
var = np.array([1, 2, 3, 4, 12, 16, 18])

# Print the data type of the array
print("Data type:", var.dtype)  
# Output: Data type: int64 (or int32, depending on your system)
# The dtype attribute shows the data type of the array elements.

Data type: int64


other Data types

In [8]:
# Create a NumPy array with floating-point values
var = np.array([1.2, 2.4, 3.5, 4.8])
print("Data type:", var.dtype)  
# Output: Data type: float64
# The array elements are of type float64 by default.

# Create a NumPy array with string values
var = np.array(["A", "B", "C"])
print("Data type:", var.dtype)  
# Output: Data type: <U1
# The array elements are of type Unicode string with maximum length 1.

# Create a NumPy array with mixed data types (integers and strings)
var = np.array(["a", "b", "c", "d", 1, 2, 3, 4])
print("Data type:", var.dtype)  
# Output: Data type: <U21
# The array elements are of type Unicode string with maximum length 21. NumPy promotes all elements to the most general type (string).

# Create a NumPy array with integer values and specify int8 data type
var = np.array([1, 2, 3, 4, 12, 16, 18], dtype=np.int8)
print("Data type:", var.dtype)  
# Output: Data type: int8
# The array elements are of type int8, which means each element is stored in 8 bits.

# Create a NumPy array with integer values and specify float32 data type
var1 = np.array([1, 2, 3, 4, 12, 16, 18], dtype="f")
print("Data type:", var1.dtype)  
# Output: Data type: float32
# The array elements are of type float32, which means each element is stored as a 32-bit floating-point number.
print(var1)  
# Output: [ 1.  2.  3.  4. 12. 16. 18.]
# The integer values are converted to float32.


Data type: float64
Data type: <U1
Data type: <U21
Data type: int8
Data type: float32
[ 1.  2.  3.  4. 12. 16. 18.]


Conversion of Data type

In [9]:
# Create a NumPy array with integer values
var = np.array([1, 2, 3, 4])

# Convert the array to float32 data type
new = np.float32(var)
print(new)  
# Output: [1. 2. 3. 4.]
# The array elements are now of type float32.

print("Data type:", new.dtype)  
# Output: Data type: float32
# The dtype attribute shows that the array elements are of type float32.

# Convert the float32 array back to integer type
new_ = np.int_(new)
print(new_)  
# Output: [1 2 3 4]
# The array elements are now of type int (default integer type, usually int64 or int32).

print("Data type:", new_.dtype)  
# Output: Data type: int64 (or int32, depending on your system)
# The dtype attribute shows that the array elements are now of integer type.

print(var)  
# Output: [1 2 3 4]
# The original array remains as integer type.

print("Data type:", var.dtype)  
# Output: Data type: int64 (or int32, depending on your system)
# The dtype attribute shows that the original array elements are of integer type.


[1. 2. 3. 4.]
Data type: float32
[1 2 3 4]
Data type: int64
[1 2 3 4]
Data type: int64


astype()

In [10]:
# Create a NumPy array with integer values
x = np.array([1, 2, 3, 4])

# Convert the array to float data type using astype
new_one = x.astype(float)
print(x)  
# Output: [1 2 3 4]
# The original array remains as integer type.

print(new_one)  
# Output: [1. 2. 3. 4.]
# The new array is converted to float type.

[1 2 3 4]
[1. 2. 3. 4.]


# Arithmetic operation on ndarray


In [11]:
# Create a 1D array with numbers
var = np.array([2, 3, 4, 5])

# Add 2 to each number in the array
varadd = var + 2
print("Added 2:", varadd)  

# Subtract 2 from each number in the array
varsub = var - 2
print("Subtracted 2:", varsub)  

# Multiply each number in the array by 2
varmul = var * 2
print("Multiplied by 2:", varmul)  


# Divide each number in the array by 2
vardiv = var / 2
print("Divided by 2:", vardiv)  

# Find the remainder when each number in the array is divided by 2
varmod = var % 2
print("Modulo 2:", varmod)  

# Square each number in the array
varpow = var ** 2
print("Squared:", varpow)  


# Divide 1 by each number in the array
varrep = 1 / var
print("Reciprocal:", varrep)  


Added 2: [4 5 6 7]
Subtracted 2: [0 1 2 3]
Multiplied by 2: [ 4  6  8 10]
Divided by 2: [1.  1.5 2.  2.5]
Modulo 2: [0 1 0 1]
Squared: [ 4  9 16 25]
Reciprocal: [0.5        0.33333333 0.25       0.2       ]


For two arrays

In [25]:
var1=np.array([2,3,4,5])
var2=np.array([6,7,8,9])
varadd=var1 + var2
varsub=var1- var2
varmul=var1 * var2
vardiv=var1 / var2
varmod=var1 % var2
varpow=var1 ** var2
varrep=1 / var2
print(varadd)
print(varsub)
print(varmul)
print(vardiv)
print(varmod)
print(varpow)
print(varrep)

[ 8 10 12 14]
[-4 -4 -4 -4]
[12 21 32 45]
[0.33333333 0.42857143 0.5        0.55555556]
[2 3 4 5]
[     64    2187   65536 1953125]
[0.16666667 0.14285714 0.125      0.11111111]


FUNCTIONS FOR ARITHMETIC OPERATION

In [26]:
var1=np.array([2,3,4,5])
var2=np.array([6,7,8,9])
varadd=np.add(var1,var2)
varsub=np.subtract(var1,var2)
varmul=np.multiply(var1,var2)
vardiv=np.divide(var1,var2)
varmod=np.mod(var1,var2)
varpow=np.power(var1,var2)
varrep=np.reciprocal(var2)
print(varadd)
print(varsub)
print(varmul)
print(vardiv)
print(varmod)
print(varpow)
print(varrep)

[ 8 10 12 14]
[-4 -4 -4 -4]
[12 21 32 45]
[0.33333333 0.42857143 0.5        0.55555556]
[2 3 4 5]
[     64    2187   65536 1953125]
[0 0 0 0]


#  Arithmetic Functions
np.min(var): Finds the smallest number in the array.

np.argmin(var): Finds the position (index) of the smallest number in the array.

np.max(var): Finds the largest number in the array.

np.argmax(var): Finds the position (index) of the largest number in the array.

np.sqrt(var): Computes the square root of each number in the array.








In [12]:
# Create a 1D array with numbers
var = np.array([49, 9, 4, 81])

# Find the minimum value in the array and its index
print("Min:", np.min(var), np.argmin(var))  

# Find the maximum value in the array and its index
print("Max:", np.max(var), np.argmax(var))  

# Calculate the square root of each number in the array
print("Sqrt:", np.sqrt(var))  


Min: 4 2
Max: 81 3
Sqrt: [7. 3. 2. 9.]


max() or min()

In [13]:
# Create a 2D array with numbers
var1 = np.array([[1, 7, 4, 5], [7, 6, 9, 8]])

# Find the maximum value along each row (axis=1)
print("Max along rows:", np.max(var1, axis=1))  

# Find the minimum value along each column (axis=0)
print("Min along columns:", np.min(var1, axis=0))  

Max along rows: [7 9]
Min along columns: [1 6 4 5]


sin() And cosin()

In [14]:
# Create a 1D array with numbers
var = np.array([1, 2, 3, 4])

# Calculate the sine of each number in the array
print("Sine:", np.sin(var))  

# Calculate the cosine of each number in the array
print("Cosine:", np.cos(var))  


Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Cosine: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


cumsum()

In [15]:
# Create a 1D array with numbers
var = np.array([1, 2, 3, 4])

# Calculate the cumulative sum of the array
print("Cumulative sum:", np.cumsum(var))  

# This calculates the sum of the elements as you go. 
# The first number is 1, the second is 1+2=3, the third is 1+2+3=6, and the fourth is 1+2+3+4=10.

Cumulative sum: [ 1  3  6 10]


# Shape

In [17]:
# Create a 2D array with numbers
var = np.array([[1, 3, 4], [2, 3, 4]])

# Print the 2D array
print(var)  
# This displays the 2D array with 2 rows and 3 columns.

# Print the shape of the 2D array
print("Shape:", var.shape)  
# This shows that the array has 2 rows and 3 columns.

[[1 3 4]
 [2 3 4]]
Shape: (2, 3)


for multidimension

In [32]:
# Create a 1D array with numbers and specify the minimum number of dimensions
var = np.array([1, 3, 4], ndmin=5)

# Print the array
print(var)  
# Output:
# [[[[[1 3 4]]]]]
# The array is displayed with extra dimensions. The original array with 3 elements is now inside 5 dimensions.

# Print the shape of the array
print("Shape:", var.shape)  
# Output: (1, 1, 1, 1, 3)
# This shows that the array has 5 dimensions. The last dimension has 3 elements, and the other dimensions have size 1.

[[[[[1 3 4]]]]]
Shape: (1, 1, 1, 1, 3)


# Reshape

In [18]:
# Create a 1D array with numbers
var = np.array([1, 2, 3, 4, 5, 6])

# Print the original 1D array
print("Original array:")
print(var)  
# This displays the 1D array with 6 elements.

# Reshape the 1D array into a 2D array with 3 rows and 2 columns
x = var.reshape(3, 2)

# Print the reshaped 2D array
print("\nReshaped array:")
print(x)  
# This shows the 1D array reshaped into a 2D array with 3 rows and 2 columns.

Original array:
[1 2 3 4 5 6]

Reshaped array:
[[1 2]
 [3 4]
 [5 6]]


 Print the reshaped 1D array

In [19]:
# Create a 1D array with numbers
var = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Print the original 1D array
print("Original array:")
print(var)  

# Reshape the 1D array into a 3D array with 3 blocks, each block having 2 rows and 2 columns
var3 = var.reshape(3, 2, 2)

# Print the reshaped 3D array
print("\nReshaped 3D array:")
print(var3)  

# Reshape the 3D array back into a 1D array
one = var3.reshape(-1)

# Print the reshaped 1D array
print("\nReshaped back to 1D array:")
print(one)  


Original array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped 3D array:
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]

Reshaped back to 1D array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]


# Broadcasting Numpy
Broadcasting in NumPy is a powerful feature that allows you to perform operations on arrays of different shapes. It automatically adjusts the shapes of arrays to make them compatible for element-wise operations.

In [20]:
# Create a 1D array with numbers
var1 = np.array([1, 2, 3])
print("Shape of var1:", var1.shape)  
# var1 is a 1D array with 3 elements.

# Create a 2D array with numbers
var2 = np.array([[1], [2], [3]])
print("Shape of var2:", var2.shape)  
# var2 is a 2D array with 3 rows and 1 column.

# Add the 1D array to the 2D array using broadcasting
print("Result of var1 + var2:")
print(var1 + var2)  
# Broadcasting aligns var1 and var2 for element-wise addition. 
# var1 is treated as a 2D array with shape (1, 3), and var2 is expanded to match this shape, allowing the addition.


Shape of var1: (3,)
Shape of var2: (3, 1)
Result of var1 + var2:
[[2 3 4]
 [3 4 5]
 [4 5 6]]


# Indexing

In [ ]:
# Create a 1D array with numbers
var = np.array([13, 4, 5, 12])

# Access the element at index 2
print(var[2])  
# Output: 5
# Index 2 refers to the third element in the array (indexing starts at 0).

# Access the element at index -2 (second to last element)
print(var[-2])  
# Output: 5
# Negative indexing counts from the end of the array. -1 is the last element, -2 is the second-to-last.


for 2D array

In [ ]:
# Create a 2D array (matrix) with numbers
var2 = np.array([[12, 13], [15, 8]])

# Print the entire 2D array
print(var2)  
# Output: 
# [[12 13]
#  [15  8]]
# This displays the 2D array with 2 rows and 2 columns.

# Access the element at row 0, column 1
print(var2[0, 1])  
# Output: 13
# The first index (0) refers to the first row, and the second index (1) refers to the second column of that row.


for 3D array

In [ ]:
# Create a 3D array with numbers
var3 = np.array([[[12, 13], [15, 8]], [[1, 2], [2, 3]]])

# Print the entire 3D array
print(var3)  
# Output:
# [[[12 13]
#   [15  8]]
# 
#  [[ 1  2]
#   [ 2  3]]]
# This displays the 3D array with two 2D arrays inside it.

# Print the number of dimensions of the 3D array
print("Number of dimensions:", var3.ndim)  
# Output: 3
# `ndim` gives the number of dimensions in the array. Here, it’s a 3D array.

print()

# Access the element at the first 2D array, second row, first column
print(var3[0, 1, 0])  
# Output: 15
# The first index (0) refers to the first 2D array, the second index (1) refers to the second row of that 2D array, and the third index (0) refers to the first column of that row.


# Slicing

In [39]:
#1D
var=np.array([11,32,33,44,54,466,77,88])
print(var)
print(var[4:])
print(var[:-5])#negative indexing'
print(var[::2])#step

[ 11  32  33  44  54 466  77  88]
[ 54 466  77  88]
[11 32 33]
[11 33 54 77]


one another example

In [ ]:
# Create a 1D array with numbers
var = np.array([11, 32, 33, 44, 54, 466, 77, 88])

# Print the entire 1D array
print(var)  
# Output: [ 11  32  33  44  54 466  77  88]
# This displays the full 1D array.

# Print elements from index 4 to the end of the array
print(var[4:])  
# Output: [ 54 466  77  88]
# This selects elements starting from index 4 to the end of the array.

# Print elements from the beginning of the array up to index -5 (not including -5)
print(var[:-5])  
# Output: [11 32 33 44]
# This selects elements from the start of the array up to the fifth element from the end.

# Print every second element of the array
print(var[::2])  
# Output: [11 33 54 77]
# This selects every second element from the array. The step size is 2.


# Iterating numpy array


In [22]:
# Create a 1D array with numbers
var = np.array([1, 2, 4, 6, 33, 556, 77, 22])

# Print the entire 1D array
print(var)  

# Iterate over each element in the array and print it
for i in var:
    print(i)  

[  1   2   4   6  33 556  77  22]
1
2
4
6
33
556
77
22


for 2D Array

In [24]:
# Create a 2D array (matrix) with numbers
var2 = np.array([[1, 2, 3, 4], [12, 11, 13, 14]])

# Print the entire 2D array
print(var2)  


# Iterate over each row in the 2D array
for i in var2:
    # Iterate over each element in the row
    for j in i:
        print(j) 


[[ 1  2  3  4]
 [12 11 13 14]]
1
2
3
4
12
11
13
14


for 3D Array

In [ ]:
# Create a 3D array with numbers
var3 = np.array([[[1, 2, 3, 4], [12, 11, 13, 14]]])

# Print the entire 3D array
print(var3)  
# Output:
# [[[ 1  2  3  4]
#   [12 11 13 14]]]
# This displays the full 3D array with one 2D array inside.

# Iterate over each element in the 3D array with its index
for i, d in np.ndenumerate(var3):
    print(i, d)  
# Output:
# (0, 0, 0) 1
# (0, 0, 1) 2
# (0, 0, 2) 3
# (0, 0, 3) 4
# (0, 1, 0) 12
# (0, 1, 1) 11
# (0, 1, 2) 13
# (0, 1, 3) 14
# Each element in the 3D array is printed with its index tuple and value.


# Copy vs View

In [26]:
# Create a 1D array with numbers
var = np.array([1, 2, 3, 4])

# Create a copy of the array
cop = var.copy()

# Modify the original array
var[2] = 50

# Print the modified original array
print("var:", var)  
# This shows the original array with the element at index 2 changed to 50.

# Print the copied array
print("copy:", cop)  
# The copied array remains unchanged because `cop` is a separate copy of the original array.


var: [ 1  2 50  4]
copy: [1 2 3 4]


# Join array

In [47]:
# Create two 1D arrays with numbers
var = np.array([1, 2, 3, 4])
var1 = np.array([5, 6, 7, 8])

# Concatenate the two arrays
join = np.concatenate((var, var1))

# Print the concatenated array
print(join)  
# This shows the combined array with elements from `var` followed by elements from `var1`.


[1 2 3 4 5 6 7 8]


for 2D arrays

In [27]:
# Create two 2D arrays (matrices)
vr = np.array([[1, 2], [3, 4]])
vr1 = np.array([[5, 6], [7, 8]])

# Concatenate the two 2D arrays along the columns (axis=1)
join = np.concatenate((vr, vr1), axis=1)

# Concatenate the two 2D arrays along the rows (axis=0)
join_ = np.concatenate((vr, vr1), axis=0)

# Print the concatenated array along columns
print(join)  
# The two matrices are combined side-by-side (columns).

# Print the concatenated array along rows
print(join_)  
# The two matrices are combined one on top of the other (rows).


[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Stack the two arrays

In [ ]:
# Create two 1D arrays with numbers
var = np.array([1, 2, 3, 4])
var1 = np.array([5, 6, 7, 8])

# Stack the two arrays along the columns (axis=1)
join = np.stack((var, var1), axis=1)
# Output:
# [[1 5]
#  [2 6]
#  [3 7]
#  [4 8]]
# This creates a 2D array where `var` and `var1` are stacked side by side as columns.

# Horizontally stack the two arrays into a single row
join1 = np.hstack((var, var1))
# Output: [1 2 3 4 5 6 7 8]
# This concatenates the arrays along the row axis, creating a single long row.

# Vertically stack the two arrays into a single column
join2 = np.vstack((var, var1))
# Output:
# [[1 2 3 4]
#  [5 6 7 8]]
# This stacks the arrays on top of each other, creating a taller 2D array.

# Stack the two arrays along the depth (height) dimension
join3 = np.dstack((var, var1))
# Output:
# [[[1 5]]
#  [[2 6]]
#  [[3 7]]
#  [[4 8]]]
# This creates a 3D array where each element in `var` and `var1` forms a depth layer.

# Print the results
print(join)
print()
print(join1)
print()
print(join2)
print()
print(join3)


# Split array



In [28]:
# Create a 1D array with numbers
var = np.array([1, 2, 3, 4, 5, 6])

# Print the original array
print(var)  

# Split the array into 3 sub-arrays
ar = np.array_split(var, 3)

# Print the list of sub-arrays
print(ar)  
# This shows the array split into 3 sub-arrays. The elements are divided as evenly as possible.

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]


for 2D Array

In [29]:
# Create a 2D array (matrix)
var = np.array([[1, 2], [3, 4], [5, 6]])

# Print the original 2D array
print(var)  

# Split the 2D array into 3 sub-arrays along the default axis (axis=0, rows)
ar = np.array_split(var, 3)

# Split the 2D array into 3 sub-arrays along axis=1 (columns)
ar1 = np.array_split(var, 3, axis=1)
# Print the results
print(ar)
print()
print(ar1)


[[1 2]
 [3 4]
 [5 6]]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int64)]


# Searching


WHERE()

In [31]:
# Create a 2D array (matrix)
var = np.array([[1, 2], [3, 4], [5, 6]])

# Print the original 2D array
print(var)  

# Split the 2D array into 3 sub-arrays along the default axis (axis=0, rows)
ar = np.array_split(var, 3)

# Split the 2D array into 3 sub-arrays along axis=1 (columns)
ar1 = np.array_split(var, 3, axis=1)

# Print the results
print(ar)
print()
print(ar1)


[[1 2]
 [3 4]
 [5 6]]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int64)]


# Searchsorted()

In [ ]:
# Create a 1D sorted array
var1 = np.array([1, 2, 3, 4, 6, 7])

# Find the index where the value 5 should be inserted to keep the array sorted
x = np.searchsorted(var1, 5)  
# Output: 4
# The index `4` is where `5` would be inserted to maintain the order of the array. 
# `5` is greater than `4` and less than `6`, so it would go at index 4.

# Alternative: Find the index where the value 5 should be inserted if elements greater than `5` are included
# x = np.searchsorted(var1, 5, side="right")  
# Output: 4
# The result is the same in this case. `side="right"` returns the index where `5` would be inserted after existing elements equal to `5`.

# Print the result
print(x)


# Sort

In [32]:
# Create a 1D array with unsorted numbers
var1 = np.array([5, 1, 2, 4, 3, 6])

# Sort the 1D array in ascending order
x = np.sort(var1)

# The array is sorted from the smallest to the largest element.

# Print the sorted 1D array
print(x)

# Create a 2D array (matrix) with unsorted numbers
var3 = np.array([[1, 6, 5, 2], [2, 4, 3, 1]])

# Sort each row of the 2D array in ascending order
sorted_var3 = np.sort(var3)


[1 2 3 4 5 6]


for stings

In [33]:
# Create a 1D array with unsorted strings
var_2 = np.array(["s", "a", "e", "b", "f"])

# Sort the array of strings in alphabetical order
sorted_var_2 = np.sort(var_2)
# The array is sorted alphabetically from 'a' to '.

# Print the sorted array of strings
print(sorted_var_2)


['a' 'b' 'e' 'f' 's']


# Filter array

In [56]:
# Create a 1D array of strings
v3 = np.array(["a", "d", "c", "f"])

# Create a boolean array where `True` indicates which elements to select
f = [True, False, True, False]

# Use boolean indexing to select elements from `v3` where the corresponding value in `f` is `True`
new_a = v3[f]
# Output: ['a' 'c']
# Only the elements where the boolean array `f` has `True` values are selected. Here, 'a' and 'c' are selected.

# Print the resulting array
print(new_a)


['a' 'c']


# Shuffle()

In [35]:
# Create a 1D array with numbers
X = np.array([1, 2, 3, 4, 5, 6])

# Shuffle the elements of the array in place
np.random.shuffle(X)
# The array `X` is modified to have its elements in a random order.

# Print the shuffled array
print(X)


[5 4 3 6 1 2]


# Unique

In [36]:
# Create a 1D array with some repeated numbers
Y = np.array([1, 2, 3, 4, 2, 4, 2, 3, 5, 2, 5, 6])

# Find unique elements, their first occurrence indices, and counts
x = np.unique(Y, return_index=True, return_counts=True)
# Output: (array([1, 2, 3, 4, 5, 6]), array([0, 1, 2, 3, 8, 11]), array([1, 4, 2, 2, 2, 1]))
# - The first array shows the unique elements in sorted order.
# - The second array shows the indices of the first occurrence of each unique element in the original array.
# - The third array shows the count of each unique element.

# Print the result
print(x)


(array([1, 2, 3, 4, 5, 6]), array([ 0,  1,  2,  3,  8, 11]), array([1, 4, 2, 2, 2, 1]))


# Resize

In [37]:
# Create a 1D array with numbers
X = np.array([1, 2, 3, 4, 5, 6])

# Resize the array to the shape (3, 2)
y = np.resize(X, (3, 2))

# Print the resized array
print(y)


[[1 2]
 [3 4]
 [5 6]]


# Flatten and Ravel

In [ ]:
# Create a 1D array with numbers
X = np.array([1, 2, 3, 4, 5, 6])

# Resize the array to the shape (3, 2)
y = np.resize(X, (3, 2))
# Output:
# [[1 2]
#  [3 4]
#  [5 6]]
# The array is reshaped into a 3x2 matrix.

# Print the resized array
print(y)

# Flatten the array in Fortran (column-major) order
flattened_f = y.flatten(order="F")
# Output: [1 3 5 2 4 6]
# The array is flattened by column-major order, which means it reads columns first.

# Print the flattened array in Fortran order
print(flattened_f)

# Flatten the array in 'K' order (keep the original order)
raveled_k = np.ravel(y, order="K")
# Output: [1 2 3 4 5 6]
# The array is flattened in the order of its original arrangement. 'K' stands for 'keep' order.

# Print the ravele


# Insert

In [38]:
# Create a 1D array with numbers
Z = np.array([1, 2, 3, 4, 5])

# Insert the value 40 at positions 2 and 4
V = np.insert(Z, (2, 4), 40)

# The value 40 is inserted at the indices 2 and 4. 
# Elements are shifted to the right to accommodate the new values.

# Print the resulting array
print(V)


[ 1  2 40  3  4 40  5]


insert in 2D array

In [39]:
# Create a 2D array (matrix)
Z = np.array([[1, 2, 3], [4, 6, 5]])

# Insert the values [40, 30] into the 2D array `Z` along the columns (axis=1)
V = np.insert(Z, 2, [40, 30], axis=1)
# Output:

# The values [40, 30] are inserted as new columns at index 2. 
# The array is updated to have these new columns.

# Print the resulting array
print(V)


[[ 1  2 40  3]
 [ 4  6 30  5]]


# Delete


In [40]:
# Create a 1D array with numbers
Z = np.array([1, 2, 3, 4, 5])

# Delete the element at index 2
d = np.delete(Z, 2)

# The element at index 2 (which is 3) is removed from the array.

# Print the resulting array
print(d)


[1 2 4 5]


# Matrix

In [64]:
# Create two matrices using np.matrix
m1 = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m2 = np.matrix([[1, 2, 3], [1, 5, 26], [72, 83, 9]])

# Print the type of m1 to confirm it is a matrix
print(type(m1))
# Output: <class 'numpy.matrix'>
# This confirms that m1 is indeed a NumPy matrix object.

print()

# Compute the matrix product of m1 and m2
result = m1.dot(m2)

# The dot() method performs matrix multiplication.

# Print the resulting matrix
print(result)


<class 'numpy.matrix'>

[[219 261  82]
 [441 531 196]
 [663 801 310]]


# Transpose and Swapaxes

In [ ]:
# Create a 3x3 matrix using np.matrix
m1 = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Transpose the matrix using np.transpose
print(np.transpose(m1))
# Output:
# [[1 4 7]
#  [2 5 8]
#  [3 6 9]]
# np.transpose() returns the transpose of the matrix. It flips rows and columns.

# Transpose the matrix using the .T attribute
print(m1.T)
# Output:
# [[1 4 7]
#  [2 5 8]
#  [3 6 9]]
# The .T attribute is a shorthand for transposing a matrix. It also flips rows and columns.

# Transpose the matrix using np.swapaxes
print(np.swapaxes(m1, 0, 1))
# Output:
# [[1 4 7]
#  [2 5 8]
#  [3 6 9]]
# np.swapaxes() swaps the axes of the matrix. Here, axis 0 (rows) and axis 1 (columns) are swapped.


# Inverse Matrix

In [ ]:
# Create a 2x2 matrix using np.matrix
var2 = np.matrix([[1, 2], [3, 4]])

# Compute the inverse of the matrix using np.linalg.inv
inverse_matrix = np.linalg.inv(var2)
# Output:
# [[-2.   1. ]
#  [ 1.5 -0.5]]
# The inverse of the matrix is a matrix such that when multiplied with the original matrix,
# it results in the identity matrix.

# Print the resulting inverse matrix
print(inverse_matrix)


# Power

In [ ]:
# Create a 2x2 matrix using np.matrix
var4 = np.matrix([[1, 2], [3, 4]])

# Print the original matrix
print(var4)
# Output:
# [[1 2]
#  [3 4]]

print()

# Compute the matrix raised to the power of 2
# Equivalent to multiplying the matrix by itself
print(np.linalg.matrix_power(var4, 2))
# Output:
# [[ 7 10]
#  [15 22]]
# This is the result of multiplying the matrix var4 by itself.

print()

# Compute the matrix raised to the power of 0
# Any matrix to the power of 0 is the identity matrix of the same size
print(np.linalg.matrix_power(var4, 0))
# Output:
# [[1 0]
#  [0 1]]
# The identity matrix. The result is a matrix where the diagonal elements are 1 and all other elements are 0.

print()

# Compute the matrix raised to the power of -2
# This is equivalent to computing the inverse of the matrix and then squaring it
print(np.linalg.matrix_power(var4, -2))
# Output:
# [[-2.   1. ]
#  [ 1.5 -0.5]]
# This is the result of taking the inverse of the matrix var4 and then squaring it.

# Note: The output may vary slightly due to floating-point precision.


# Determinant

In [ ]:
# Create a 2x2 matrix
var5 = np.matrix([[1, 2], [3, 4]])

# Compute the determinant of var5
det_var5 = np.linalg.det(var5)
print(det_var5)
# Output: -2.0000000000000004
# The determinant of a 2x2 matrix can be computed as (ad - bc) where the matrix is [[a, b], [c, d]].

print()

# Create a 3x3 matrix
var6 = np.matrix([[1, -6, -3], [4, 9, -6], [7, -1, 9]])

# Compute the determinant of var6
det_var6 = np.linalg.det(var6)
print(det_var6)
# Output: -168.00000000000003
# The determinant of a 3x3 matrix is computed using a more complex formula involving sums and products of its elements.


# ********** Numpy Basics End **********